alias vim='nvim'
alias raspi_NAS='ssh pi@raspi_extender.local -p 50022 -i ~/.ssh/raspi3b'
alias raspi_camera='ssh pi@raspicamera.local -p 50022 -i ~/.ssh/id_rsa_raspi3b'
alias raspi4nas='ssh pi@raspi4nas.local -p 50022 -i ~/.ssh/raspi4_nas'
alias py='python'
